apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ctfd
  namespace: traefik
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-ctfd
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certissuer }}
  dnsNames:
  - {{ .Values.Host }}
  - "*.{{ .Values.Host }}"
