apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-ctfd
  namespace: ctfd
  labels:
    kube-ctf.downunderctf.com/type: web
    kube-ctf.downunderctf.com/name: ctfd
spec:
  entryPoints:
    - web
    - websecure
  tls:
    certResolver: default
  routes:
    - match: Host(`{{ .Values.Host }}`)
      kind: Rule
      priority: 12
      middlewares:
      - name: hsts
      services:
      - name: ctfd-website
        port: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: ctfd
spec:
  headers:
    stsSeconds: 15552000
    forceSTSHeader: true
    stsIncludeSubdomains: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hsts
  namespace: ctfd
spec:
  headers:
    stsSeconds: 15552000
    forceSTSHeader: true
    stsIncludeSubdomains: true
---
