apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: reyio@vivaldi.net # Reference the email from the secret
    privateKeySecretRef:
      name: cert-manager-letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: api-token
